#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : spyder-notebook
Version  : 0.1.3
Release  : 15
URL      : https://files.pythonhosted.org/packages/88/52/1c39b7b162cad5e243216e77dcc6c584e57d2c3776598927cb438aea479e/spyder-notebook-0.1.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/88/52/1c39b7b162cad5e243216e77dcc6c584e57d2c3776598927cb438aea479e/spyder-notebook-0.1.3.tar.gz
Summary  : Jupyter notebook integration with Spyder
Group    : Development/Tools
License  : MIT
Requires: spyder-notebook-python3
Requires: spyder-notebook-python
Requires: QtPy
Requires: nbformat
Requires: notebook
Requires: psutil
Requires: requests
BuildRequires : buildreq-distutils3

%description
# Spyder notebook plugin
Spyder plugin to use Jupyter notebooks inside Spyder. Currently it supports
basic functionality such as creating new notebooks, opening any notebook in
your filesystem and saving notebooks at any location.

%package python
Summary: python components for the spyder-notebook package.
Group: Default
Requires: spyder-notebook-python3

%description python
python components for the spyder-notebook package.


%package python3
Summary: python3 components for the spyder-notebook package.
Group: Default
Requires: python3-core

%description python3
python3 components for the spyder-notebook package.


%prep
%setup -q -n spyder-notebook-0.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536550301
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
